### ISSUE TITLE
Not installable using PIP on Fedora 26

### ISSUE THREAD

**Issue by Yamakasi** [jed/certbot-route53#6]
Hi I try to install this package using PIP on Fedora 26 and get this:

# pip install -U certbot-route53

...

Installing collected packages: setuptools, zope.interface, ConfigArgParse, six, configobj, pytz, pyrfc3339, idna, pycparser, cffi, ipaddress, cryptography, PyOpenSSL, zope.event, zope.component, urllib3, chardet, certifi, requests, funcsigs, pbr, mock, acme, future, parsedatetime, certbot, python-dateutil, jmespath, docutils, botocore, futures, s3transfer, boto3, certbot-dns-route53, certbot-route53
  Found existing installation: setuptools 36.2.0
    Uninstalling setuptools-36.2.0:
      Successfully uninstalled setuptools-36.2.0
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/site-packages/pip/locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 365, in __init__
    self._finalize_requires()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 372, in _finalize_requires
    if not self.install_requires:
AttributeError: Distribution instance has no attribute 'install_requires'

What am I doing wrong ?

**Comment by mslinn** [comment]
I did not see any instructions to run this:

    pip install -U certbot-route53

But I see that command appears to install useful utilities, such as `certbot-route53` and `certbot-dns-route53`. Are the installation instructions for this package incomplete?
